const {
  telebirrAgentId,
  telebirrAgentPassword,
  INTERNAL_API_HOST,
  ENDPOINT_POST_REVERSE_TRANSACTION,
  ENDPOINT_POST_DEBIT_FROM_ACCOUNT,
  INTERNAL_API_BASE_PATH,
  INTERNAL_API_TOKEN,
  TELEBIRR_ENDPOINT_POST_GENERATE_TOKEN,
  TELEBIRR_HOST_URL,
  TELEBIRR_ENDPOINT_GET_ACCOUNT_INFO,
  TELEBIRR_ENDPOINT_POST_TRANSFER_FUND,
} = process.env;

module.exports = {
  telebirrAgentId,
  telebirrAgentPassword,
  debitFromAccountUrl:
    INTERNAL_API_HOST +
    INTERNAL_API_BASE_PATH +
    ENDPOINT_POST_DEBIT_FROM_ACCOUNT,
  reverseTransactionUrl:
    INTERNAL_API_HOST +
    INTERNAL_API_BASE_PATH +
    ENDPOINT_POST_REVERSE_TRANSACTION,
  INTERNAL_API_TOKEN,
  telebirrGenerateTokenUrl:
    TELEBIRR_HOST_URL + TELEBIRR_ENDPOINT_POST_GENERATE_TOKEN,
  telebirrAccountInfoUrl:
    TELEBIRR_HOST_URL + TELEBIRR_ENDPOINT_GET_ACCOUNT_INFO,
  telebirrFundTransferUrl:
    TELEBIRR_HOST_URL + TELEBIRR_ENDPOINT_POST_TRANSFER_FUND,
};
